/***
 * SCRIPT BD GESTION DECOMPTES
 * SQL SERVER
 * 
 * ZGUIOUAR 
 */

-- DROP TABLES

DROP TABLE PROFIL_ROLE;
DROP TABLE ROLE;
DROP TABLE AUTORISATION;
DROP TABLE PROFIL;
DROP TABLE BON_RECEPTION;
DROP TABLE UTILISATEUR;
DROP TABLE ATTACHEMENT;
DROP TABLE BON_COMMANDE;
DROP TABLE DECOMPTE;
DROP TABLE MARCHE;
DROP TABLE SITE;
DROP TABLE TERMINAL;
DROP TABLE PORT;

-- GESTION DES UTILISATEURS

CREATE TABLE
    UTILISATEUR
    (
        ID_USER INTEGER NOT NULL IDENTITY,
        USERNAME VARCHAR(40) NOT NULL,
        PWD VARCHAR(200) NOT NULL,
        EMAIL VARCHAR(50) NOT NULL,
        PWD_RESET VARCHAR(50) ,
        PWD_CLAIR VARCHAR(200) ,
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_ID_USER PRIMARY KEY (ID_USER)
    );
	
CREATE TABLE
    ROLE
    (
        ID_ROLE INTEGER  NOT NULL IDENTITY,
        COD_ROLE VARCHAR(100) NOT NULL,
        LIB_ROLE VARCHAR(100) NOT NULL,
        NUM_ORDRE INTEGER  NOT NULL,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        CONSTRAINT PK_ROLE PRIMARY KEY (ID_ROLE),
        CONSTRAINT INDEX_UNIQUE_COD_ROLE UNIQUE (COD_ROLE),
        CONSTRAINT INDEX_UNIQUE_LIB_ROLE UNIQUE (LIB_ROLE)
    );
	
CREATE TABLE
    PROFIL
    (
        ID_PROFIL INTEGER  NOT NULL IDENTITY,
        COD_PROFIL VARCHAR(30) NOT NULL,
        LIB_PROFIL VARCHAR(100) NOT NULL,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_PROFIL PRIMARY KEY (ID_PROFIL),
        CONSTRAINT INDEX_UNIQUE_COD_PROFIL UNIQUE (COD_PROFIL),
        CONSTRAINT INDEX_UNIQUE_LIB_PROFIL UNIQUE (LIB_PROFIL)
    );

CREATE TABLE
    PROFIL_ROLE
    (
        ID_PROFIL INTEGER  NOT NULL,
        ID_ROLE INTEGER  NOT NULL,
        CONSTRAINT PK_PROFIL_ROLE PRIMARY KEY (ID_PROFIL, ID_ROLE)
    );
ALTER TABLE
    PROFIL_ROLE ADD CONSTRAINT FK_ID_PROFIL_PROFIL_ROLE FOREIGN KEY (ID_PROFIL) REFERENCES PROFIL (ID_PROFIL);
ALTER TABLE
    PROFIL_ROLE ADD CONSTRAINT FK_ID_ROLE_PROFIL_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID_ROLE);      
	
CREATE TABLE
    PORT
    (
        ID_PORT INTEGER  NOT NULL IDENTITY,
        COD_PORT VARCHAR(50) NOT NULL,
        LIB_PORT VARCHAR(100) NOT NULL,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        CONSTRAINT PK_PORT PRIMARY KEY (ID_PORT),
        CONSTRAINT INDEX_UNIQUE_COD_PORT UNIQUE (COD_PORT),
        CONSTRAINT INDEX_UNIQUE_LIB_PORT UNIQUE (LIB_PORT)
    );
	
CREATE TABLE
    TERMINAL
    (
        ID_TERMINAL INTEGER  NOT NULL IDENTITY,
        ID_PORT INTEGER,
        COD_TERMINAL VARCHAR(50) NOT NULL,
        LIB_TERMINAL VARCHAR(100) NOT NULL,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        CONSTRAINT PK_TERMINAL PRIMARY KEY (ID_TERMINAL)
    );    
ALTER TABLE
    TERMINAL ADD CONSTRAINT FK_ID_PORT_TERMINAL FOREIGN KEY (ID_PORT) REFERENCES PORT (ID_PORT);
ALTER TABLE 
	TERMINAL ADD CONSTRAINT INDEX_COD_TERMINAL_TERMINAL UNIQUE (COD_TERMINAL);     

CREATE TABLE
    SITE
    (
        ID_SITE INTEGER  NOT NULL IDENTITY,
        ID_TERMINAL INTEGER NOT NULL,
        COD_SITE VARCHAR(50) NOT NULL,
        LIB_SITE VARCHAR(100) NOT NULL,
        COD_ISO VARCHAR(50) ,
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_SITE PRIMARY KEY (ID_SITE),
        CONSTRAINT INDEX_UNIQUE_COD_SITE UNIQUE (COD_SITE)
    );
ALTER TABLE
    SITE ADD CONSTRAINT FK_ID_TERMINAL_SITE FOREIGN KEY (ID_TERMINAL) REFERENCES TERMINAL (ID_TERMINAL);
	

CREATE TABLE
    AUTORISATION
    (
        ID_AUTORISATION INTEGER NOT NULL IDENTITY,
        ID_USER INTEGER NOT NULL,
        ID_SITE INTEGER NOT NULL,
        ID_PROFIL INTEGER  NOT NULL,
        CONSTRAINT PK_AUTORISATION PRIMARY KEY (ID_AUTORISATION),
        CONSTRAINT INDEX_UNIQUE_AUTORISATION UNIQUE (ID_USER, ID_SITE, ID_PROFIL)
    );
ALTER TABLE
    AUTORISATION ADD CONSTRAINT FK_ID_USER_AUTORISATION FOREIGN KEY (ID_USER) REFERENCES UTILISATEUR (ID_USER);
ALTER TABLE
    AUTORISATION ADD CONSTRAINT FK_ID_SITE_AUTORISATION FOREIGN KEY (ID_SITE) REFERENCES SITE (ID_SITE); 
ALTER TABLE
    AUTORISATION ADD CONSTRAINT FK_ID_PROFIL_AUTORISATION FOREIGN KEY (ID_PROFIL) REFERENCES PROFIL (ID_PROFIL);	
	
-- GESTION DECOMPTE
	
CREATE TABLE
    MARCHE
    (
        ID_MARCHE INTEGER  NOT NULL IDENTITY,
        ID_SITE INTEGER NOT NULL ,
        NUM_MARCHE VARCHAR(50) NOT NULL,
        COD_FOURNISSEUR VARCHAR(50) NOT NULL,
        LIB_FOURNISSEUR VARCHAR(100),
        LIB_MARCHE VARCHAR(100),
        DESCRIPTION VARCHAR(MAX),
        DATE_DEMARAGE DATE,
        DATE_FIN DATE,
        MONTANT FLOAT not null,
        DEVISE VARCHAR(20),
        BUDGET VARCHAR(60),
        FLAG_CLOTURE VARCHAR(1) DEFAULT 'N';
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_MARCHE PRIMARY KEY (ID_MARCHE)
    );
 ALTER TABLE
    MARCHE ADD CONSTRAINT FK_ID_SITE_MARCHE FOREIGN KEY (ID_SITE) REFERENCES SITE (ID_SITE);

CREATE TABLE
   BORDEREAU_PRIX
    (
        ID_BORDEREAU_PRIX INTEGER  NOT NULL IDENTITY,
        ID_MARCHE INTEGER,
        DESIGNIATION VARCHAR(100),
        UNITE VARCHAR(50),
        QTE FLOAT,
        PRIX_UNITAIRE FLOAT,
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_BORDEREAU_PRIX PRIMARY KEY (ID_BORDEREAU_PRIX)
    );
 ALTER TABLE
    BORDEREAU_PRIX ADD CONSTRAINT FK_ID_MARCHE_BORDEREAU_PRIX FOREIGN KEY (ID_MARCHE) REFERENCES MARCHE (ID_MARCHE);    

CREATE TABLE
    BON_COMMANDE
    (
        ID_BON_COMMANDE INTEGER  NOT NULL IDENTITY,
        ID_SITE INTEGER NOT NULL ,
        NUM_BON_COMMANDE VARCHAR(50) NOT NULL,
        COD_FOURNISSEUR VARCHAR(50) NOT NULL,
        LIB_FOURNISSEUR VARCHAR(100),
        LIB_BON_COMMANDE VARCHAR(100),
        DATE_COMMANDE DATE,
        DEVISE VARCHAR(20),
        MONTANT FLOAT,
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_BON_COMMANDE PRIMARY KEY (ID_BON_COMMANDE)
    );
 ALTER TABLE
    BON_COMMANDE ADD CONSTRAINT FK_ID_SITE_BON_COMMANDE FOREIGN KEY (ID_SITE) REFERENCES SITE (ID_SITE);

CREATE TABLE
    DECOMPTE
    (
        ID_DECOMPTE INTEGER  NOT NULL IDENTITY,
        ID_MARCHE INTEGER,
        DATE_ETABLISSEMENT DATE,
        FLAG_DERNIER  VARCHAR(1) ,
        MONTANT_TTC  FLOAT,
        RETENU_GARANTIE FLOAT,
        PENALITE_RETARD FLOAT,
        REVISION_PRIX FLOAT,
        AUTRES_RETENUES FLOAT,
        RETENUE_SOURCE FLOAT,       
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_DECOMPTE PRIMARY KEY (ID_DECOMPTE)
    );
 ALTER TABLE
    DECOMPTE ADD CONSTRAINT FK_ID_MARCHE_DECOMPTE FOREIGN KEY (ID_MARCHE) REFERENCES MARCHE (ID_MARCHE);

CREATE TABLE
    ATTACHEMENT
    (
        ID_ATTACHEMENT INTEGER  NOT NULL IDENTITY,
        ID_MARCHE INTEGER,
        ID_BON_COMMANDE INTEGER,
        ID_DECOMPTE INTEGER,
        DATE_ETABLISSEMENT DATE,
        DATE_DEBUT DATE,
        DATE_FIN DATE,
        FLAG_DERNIER  VARCHAR(1) ,
        MONTANT FLOAT,      
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_ATTACHEMENT PRIMARY KEY (ID_ATTACHEMENT)
    );
ALTER TABLE
    ATTACHEMENT ADD CONSTRAINT FK_ID_MARCHE_ATTACHEMENT FOREIGN KEY (ID_MARCHE) REFERENCES MARCHE (ID_MARCHE);
ALTER TABLE
    ATTACHEMENT ADD CONSTRAINT FK_ID_BON_COMMANDE_ATTACHEMENT FOREIGN KEY (ID_BON_COMMANDE) REFERENCES BON_COMMANDE (ID_BON_COMMANDE);   
ALTER TABLE
    ATTACHEMENT ADD CONSTRAINT FK_ID_DECOMPTE_ATTACHEMENT FOREIGN KEY (ID_DECOMPTE) REFERENCES DECOMPTE (ID_DECOMPTE);
        	
CREATE TABLE
    BON_RECEPTION
    (
        ID_BON_RECEPTION INTEGER  NOT NULL IDENTITY,
        ID_ATTACHEMENT INTEGER  NOT NULL,
        DESIGNIATION_BON_RECEPTION VARCHAR(100),
        DATE_COMMANDE DATE,
        DATE_RECEPTION DATE,
        DELAIS VARCHAR(50),
        UNITE VARCHAR(50),
        QTE FLOAT,
        PRIX_UNITAIRE FLOAT,
        MONTANT FLOAT,
        TVA FLOAT,
        MO VARCHAR(100),
        OT VARCHAR(100),        
        IND_SUPP INT DEFAULT 1,
        USER_CREAT VARCHAR(20) NOT NULL,
        DAT_CREAT DATETIME DEFAULT GETDATE() NOT NULL,
        USER_MODIF VARCHAR(20) ,
        DAT_MODIF DATETIME,
        CONSTRAINT PK_BON_RECEPTION PRIMARY KEY (ID_BON_RECEPTION)
    );
 ALTER TABLE
    BON_RECEPTION ADD CONSTRAINT FK_ID_BON_RECEPTION_BON_RECEPTION FOREIGN KEY (ID_BON_COMMANDE) REFERENCES BON_COMMANDE (ID_BON_COMMANDE);
 ALTER TABLE
    BON_RECEPTION ADD CONSTRAINT FK_ID_ATTACHEMENT_BON_RECEPTION FOREIGN KEY (ID_ATTACHEMENT) REFERENCES ATTACHEMENT (ID_ATTACHEMENT);